import type { HubSpotMenu } from "../../../types/hubspot";

const mockFooterMenu: HubSpotMenu = {
  activeBranch: false,
  activeNode: false,
  blogNode: false,
  categoryId: null,
  children: [
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 1", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 2", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 3", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 4", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 5", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 6", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: null,
      isNonLinkingNode: null,
      isPublished: null,
      label: "Products & Services",
      level: 1,
      linkTarget: null,
      live: null,
      nodeType: null,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "#",
      urlParamStr: null,
      urlWithoutAnchor: null,
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 1", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 2", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 3", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 4", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 5", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 6", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: null,
      isNonLinkingNode: null,
      isPublished: null,
      label: "Areas of Expertise",
      level: 1,
      linkTarget: null,
      live: null,
      nodeType: null,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "#",
      urlParamStr: null,
      urlWithoutAnchor: null,
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 1", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 2", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 3", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 4", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 5", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 6", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: null,
      isNonLinkingNode: null,
      isPublished: null,
      label: "About",
      level: 1,
      linkTarget: null,
      live: null,
      nodeType: null,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "#",
      urlParamStr: null,
      urlWithoutAnchor: null,
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 1", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 2", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 3", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 4", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 5", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
        { activeBranch: false, activeNode: false, blogNode: false, categoryId: null, children: null, contentGroupId: null, contentType: null, errorMessage: null, guid: null, isDeleted: null, isNonLinkingNode: null, isPublished: null, label: "Sub-navigation text 6", level: 2, linkTarget: null, live: null, nodeType: null, pageId: null, pageTitle: null, parentGuid: null, slug: null, state: null, subcategory: null, topLevelAncestorGuid: null, url: "#", urlParamStr: null, urlWithoutAnchor: null },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: null,
      isNonLinkingNode: null,
      isPublished: null,
      label: "Careers",
      level: 1,
      linkTarget: null,
      live: null,
      nodeType: null,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "#",
      urlParamStr: null,
      urlWithoutAnchor: null,
    },
  ],
  contentGroupId: null,
  contentType: null,
  errorMessage: null,
  guid: null,
  isDeleted: null,
  isNonLinkingNode: null,
  isPublished: null,
  label: null,
  level: null,
  linkTarget: null,
  live: null,
  nodeType: null,
  pageId: null,
  pageTitle: null,
  parentGuid: null,
  slug: null,
  state: null,
  subcategory: null,
  topLevelAncestorGuid: null,
  url: null,
  urlParamStr: null,
  urlWithoutAnchor: null,
};

window.Tosoh = {
  footerNavigationMenu: mockFooterMenu,
  ...window.Tosoh,
};

export default mockFooterMenu;
