export const mockKioskDocumentsFiltersResponse = {
  total: 43,
  results: [
    {
      id: '89608811146',
      createdAt: '2022-10-27T01:08:00.923Z',
      updatedAt: '2023-08-07T16:03:26.315Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hbdrive-brochure',
      name: 'HbDrive® - Do more with less - Test diabetes the better way',
      displayIndex: 1,
      values: {
        product_type: {
          id: '5',
          name: 'Automation',
          label: 'Automation',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 4,
        },
        title: 'HbDrive<sup>®</sup><br>Do more with less - Test diabetes the better way',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '89608811148',
      createdAt: '2022-10-27T01:08:00.937Z',
      updatedAt: '2023-03-22T09:11:03.969Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: '501rp',
      name: "501RP+ Data management software for Tosoh's Clinical HPLC and Immunoassay Systems",
      displayIndex: 2,
      values: {
        product_type: {
          id: '5',
          name: 'Automation',
          label: 'Automation',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 4,
        },
        title:
          "501RP<sup>+</sup><br>Data management software for Tosoh's Clinical HPLC and Immunoassay Systems",
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90538453524',
      createdAt: '2022-11-04T14:58:18.642Z',
      updatedAt: '2023-03-22T09:11:20.945Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'evoline',
      name: 'EVOLINE™ Data Management and Laboratory Automation',
      displayIndex: 3,
      values: {
        product_type: {
          id: '5',
          name: 'Automation',
          label: 'Automation',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 4,
        },
        title: 'EVOLINE™<br>Data Management and Laboratory Automation',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90538453527',
      createdAt: '2022-11-04T15:05:00.595Z',
      updatedAt: '2023-02-22T15:29:19.072Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'trcready-80',
      name: 'TRCReady®-80',
      displayIndex: 4,
      values: {
        product_type: {
          id: '4',
          name: 'TRCR',
          label: 'TRCR',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 3,
        },
        title:
          'TRCReady<sup>®</sup><br>Fully Automated and Fast  High Quality Nucleic Acid Amplification Test',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90525934400',
      createdAt: '2022-11-04T15:07:57.574Z',
      updatedAt: '2024-11-04T17:41:09.463Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723g11-b-thal',
      name: 'Tosoh Automated Glycohemoglobin Analyzer HLC-723G11 ß-Thalassaemia Analysis Mode',
      displayIndex: 5,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title:
          'Tosoh Automated Glycohemoglobin Analyzer HLC-723G11<br>ß-Thalassaemia Analysis Mode',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90726793359',
      createdAt: '2022-11-06T19:59:35.291Z',
      updatedAt: '2024-11-06T14:55:42.608Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-360-the-special-one-automated-immunoassay-analysers',
      name: 'AIA-360 The Special One - Spec sheet',
      displayIndex: 7,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'AIA<sup>®</sup>-360<br>The Special One<br>Spec sheet',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814484',
      createdAt: '2022-11-07T22:29:00.199Z',
      updatedAt: '2023-03-22T16:19:15.302Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723-g11standard-analysis-mode',
      name: 'Tosoh Automated Glycohemoglobin Analyzer HLC-723® G11 Standard Analysis Mode',
      displayIndex: 10,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title:
          'Tosoh Automated Glycohemoglobin Analyzer HLC-723<sup>®</sup> G11<br>Standard Analysis Mode',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814485',
      createdAt: '2022-11-07T22:29:00.205Z',
      updatedAt: '2023-03-22T16:23:44.152Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723gx',
      name: 'Tosoh Automated Glycohemoglobin Analyzer HLC-723 GX',
      displayIndex: 11,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'Tosoh Automated Glycohemoglobin Analyzer HLC-723<sup>®</sup> GX',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814486',
      createdAt: '2022-11-07T22:29:00.211Z',
      updatedAt: '2024-11-04T17:26:13.734Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723g8beta-thal',
      name: 'Tosoh Automated Glycohemoglobin AnalyzerHLC-723G8ß-Thalassaemia Analysis Mode',
      displayIndex: 12,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title:
          'Tosoh Automated Glycohemoglobin Analyzer HLC-723<sup>®</sup> G8<br>ß-Thalassaemia Analysis Mode',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814487',
      createdAt: '2022-11-07T22:29:00.218Z',
      updatedAt: '2023-02-22T15:14:31.240Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723g8var',
      name: 'Tosoh Automated Glycohemoglobin AnalyzerHLC-723G8Variant Analysis Mode',
      displayIndex: 13,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title:
          'Tosoh Automated Glycohemoglobin Analyzer HLC-723<sup>®</sup> G8<br>Variant Analysis Mode',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814488',
      createdAt: '2022-11-07T22:29:00.223Z',
      updatedAt: '2023-08-07T16:16:14.773Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723-g11-variant-analysis-mode',
      name: 'Tosoh Automated Glycohemoglobin Analyzer HLC-723® G11 Variant Analysis Mode',
      displayIndex: 14,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title:
          'Tosoh Automated Glycohemoglobin Analyzer HLC-723<sup>®</sup> G11<br>Variant Analysis Mode',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814489',
      createdAt: '2022-11-07T22:29:00.229Z',
      updatedAt: '2023-05-05T13:07:50.108Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'gx-g8-g11-performance',
      name: 'GX | G8 | G11 Performance On All Fronts - Total Peace Of Mind',
      displayIndex: 15,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'GX | G8 | G11<br>Performance on all fronts - Total peace of mind',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814491',
      createdAt: '2022-11-07T22:29:00.241Z',
      updatedAt: '2022-12-01T15:30:55.240Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'g8-the-benchmark',
      name: 'G8 - The benchmark of performance',
      displayIndex: 17,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'G8<br>The benchmark of performance',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814492',
      createdAt: '2022-11-07T22:29:00.247Z',
      updatedAt: '2024-12-03T09:41:14.231Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'g11-tosohs-greatest-performance',
      name: "G11 - Tosoh's greatest performance",
      displayIndex: 18,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: "G11<br>Tosoh's greatest performance",
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814493',
      createdAt: '2022-11-07T22:29:00.253Z',
      updatedAt: '2024-10-29T16:54:42.845Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-900-the-flexible-grower-spec-sheet2',
      name: 'AIA®-900The solution for growing laboratories',
      displayIndex: 19,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'AIA<sup>®</sup>-900<br>The solution for growing laboratories',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814496',
      createdAt: '2022-11-07T22:29:00.270Z',
      updatedAt: '2024-10-29T16:55:12.882Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-900the-solution-for-growing-laboratories',
      name: 'AIA®-900The solution for growing laboratories',
      displayIndex: 20,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'AIA<sup>®</sup>-900<br>The solution for growing laboratories',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814494',
      createdAt: '2022-11-07T22:29:00.259Z',
      updatedAt: '2023-08-07T16:21:49.701Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'veterinary-testing-with-aia-360',
      name: 'Easy veterinary testing with AIA®-360',
      displayIndex: 21,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'Easy veterinary testing with AIA<sup>®</sup>-360',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814495',
      createdAt: '2022-11-07T22:29:00.264Z',
      updatedAt: '2023-08-07T16:20:45.746Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-2000-the-hard-worker',
      name: 'AIA®-2000 The Hard Worker',
      displayIndex: 22,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'AIA<sup>®</sup>-2000<br>The Hard Worker',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814497',
      createdAt: '2022-11-07T22:29:00.276Z',
      updatedAt: '2024-08-30T13:25:39.728Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-360-the-special-one',
      name: 'AIA®\n-360\nThe Special One',
      displayIndex: 23,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title: 'AIA<sup>®</sup>-360<br>The Special One',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814498',
      createdAt: '2022-11-07T22:29:00.282Z',
      updatedAt: '2025-06-18T07:56:09.353Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'automated-immunoassay-analysers',
      name: 'Automated Immunoassay Analysers AIA®-360 I AIA®-900 I AIA®-2000 - Always the right choice for your lab',
      displayIndex: 24,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title:
          'Automated Immunoassay Analysers AIA<sup>®</sup>-360 I AIA<sup>®</sup>-900 I AIA<sup>®</sup>-2000<br>Always the right choice for your lab',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814499',
      createdAt: '2022-11-07T22:29:00.288Z',
      updatedAt: '2023-08-07T16:23:55.299Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-pack-reagents',
      name: 'AIA-PACK® Reagents for AIA®-360 • AIA®-900 • AIA®-2000',
      displayIndex: 25,
      values: {
        product_type: {
          id: '2',
          name: 'AIA',
          label: 'AIA',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
        title:
          'AIA-PACK<sup>®</sup> Reagents for AIA<sup>®</sup>-360 • AIA<sup>®</sup>-900 • AIA<sup>®</sup>-2000',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814500',
      createdAt: '2022-11-07T22:29:00.294Z',
      updatedAt: '2023-08-07T16:13:34.404Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'cl-aia-pack',
      name: 'The Tosoh CL AIA-PACK® twin cup - How does it work?',
      displayIndex: 26,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'The Tosoh CL AIA-PACK<sup>®</sup> twin cup - How does it work?',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814501',
      createdAt: '2022-11-07T22:29:00.299Z',
      updatedAt: '2024-10-29T16:43:04.702Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'cl-aia-pack-reagents',
      name: 'CL AIA-PACK® Reagents',
      displayIndex: 27,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'CL AIA-PACK<sup>®</sup> Reagents',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814502',
      createdAt: '2022-11-07T22:29:00.305Z',
      updatedAt: '2023-08-07T16:12:16.136Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-cl1200-the-sensitive-performer-specifications-sheet',
      name: 'AIA®-CL1200 - The Sensitive Performer - Specifications Sheet',
      displayIndex: 28,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'AIA<sup>®</sup>-CL1200<br>The Sensitive Performer<br>Specifications Sheet',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814503',
      createdAt: '2022-11-07T22:29:00.311Z',
      updatedAt: '2023-08-07T16:11:22.369Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-cl2400-the-sensitive-performer-specifications-sheet',
      name: 'AIA®-CL2400 - The Sensitive Performer - Specifications Sheet',
      displayIndex: 29,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'AIA<sup>®</sup>-CL2400<br>The Sensitive Performer<br>Specifications Sheet',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814504',
      createdAt: '2022-11-07T22:29:00.316Z',
      updatedAt: '2023-03-22T18:33:28.077Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'the-aia-cl1200-the-new-generation-mid-size',
      name: 'The AIA®-CL1200 - The new generation mid–size analyser',
      displayIndex: 30,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'The AIA<sup>®</sup>-CL1200<br>The new generation mid–size analyser',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814505',
      createdAt: '2022-11-07T22:29:00.322Z',
      updatedAt: '2023-03-22T16:15:30.345Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'the-aia-cl2400the-first-of-the-newest-generation',
      name: 'The AIA®-CL2400 - The first of the newest generation',
      displayIndex: 31,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'The AIA<sup>®</sup>-CL2400<br>The first of the newest generation',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814506',
      createdAt: '2022-11-07T22:29:00.328Z',
      updatedAt: '2023-03-22T09:09:38.035Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'we-want-to-be-parents',
      name: 'We want to be parents…',
      displayIndex: 32,
      values: {
        product_type: {
          id: '6',
          name: 'Immunoassays',
          label: 'Immunoassays',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 5,
        },
        title: 'We want to be parents…',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814507',
      createdAt: '2022-11-07T22:29:00.333Z',
      updatedAt: '2023-08-07T16:25:29.396Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'sepsis-diagnosis-made-clear',
      name: 'Sepsis - Diagnosis made clear through PRESEPSIN testing',
      displayIndex: 33,
      values: {
        product_type: {
          id: '6',
          name: 'Immunoassays',
          label: 'Immunoassays',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 5,
        },
        title: 'Sepsis - Diagnosis made clear through PRESEPSIN testing',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '90836814510',
      createdAt: '2022-11-07T22:29:00.351Z',
      updatedAt: '2022-12-01T15:22:13.778Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'corona-virus-rna-detection',
      name: 'New CORONA VIRUS RNA detection reagent',
      displayIndex: 36,
      values: {
        product_type: {
          id: '4',
          name: 'TRCR',
          label: 'TRCR',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 3,
        },
        title: 'New CORONA VIRUS RNA detection reagent',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '99414800738',
      createdAt: '2023-01-21T22:06:00.886Z',
      updatedAt: '2023-05-16T14:06:53.479Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-cl-assay-menu-specifications',
      name: 'AIA-CL  |  Assay Menu Specifications',
      displayIndex: 37,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'AIA<sup>®</sup>-CL  |  Assay Menu Specifications',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '107533916826',
      createdAt: '2023-03-22T16:56:25.357Z',
      updatedAt: '2023-03-22T18:17:12.806Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'biotin-free-immunoassays-by-tosoh-leaflet',
      name: 'Biotinfreie Immunoassays von Tosoh - Leaflet',
      displayIndex: 38,
      values: {
        product_type: {
          id: '6',
          name: 'Immunoassays',
          label: 'Immunoassays',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 5,
        },
        title: 'Tosoh Immunoassays sind "Biotin frei" - Keine Biotin Interferenz',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '107536502122',
      createdAt: '2023-03-22T17:07:44.090Z',
      updatedAt: '2023-03-22T18:09:50.489Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'biotin-free-immunoassays-by-tosoh-physicians',
      name: 'Biotinfreie Immunoassays von Tosoh - Physicians',
      displayIndex: 39,
      values: {
        product_type: {
          id: '6',
          name: 'Immunoassays',
          label: 'Immunoassays',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 5,
        },
        title: 'Biotinfreie Immunoassays von Tosoh - Physicians',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '107533917104',
      createdAt: '2023-03-22T17:10:26.596Z',
      updatedAt: '2023-05-09T07:57:44.342Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'biotin-free-immunoassays-by-tosoh-labs',
      name: 'Biotinfreie Immunoassays von Tosoh - Labs',
      displayIndex: 40,
      values: {
        product_type: {
          id: '6',
          name: 'Immunoassays',
          label: 'Immunoassays',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 5,
        },
        title: 'Biotinfreie Immunoassays von Tosoh - Labs',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '107533917106',
      createdAt: '2023-03-22T17:12:22.810Z',
      updatedAt: '2024-04-24T12:09:33.989Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-cl300-the-small-giant',
      name: 'AIA®-CL300 - The Small Giant',
      displayIndex: 41,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'AIA<sup>®</sup>-CL300<br>The Small Giant',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '114771957359',
      createdAt: '2023-05-09T08:04:10.597Z',
      updatedAt: '2023-05-11T14:14:41.009Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'aia-cl300-the-small-giant-specifications-sheet',
      name: 'AIA®-CL300 - The Small Giant^- Specifications Sheet',
      displayIndex: 42,
      values: {
        product_type: {
          id: '3',
          name: 'AIA-CL',
          label: 'AIA-CL',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
        title: 'AIA<sup>®</sup>-CL300<br>The Small Giant<br>Specifications Sheet',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '152901305761',
      createdAt: '2024-01-12T21:24:09.807Z',
      updatedAt: '2024-01-12T21:35:09.241Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'tosoh-hemoglobin-variants-library',
      name: 'Tosoh Hemoglobin Variants Library',
      displayIndex: 43,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'Tosoh Hemoglobin Variants Library',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '182409205590',
      createdAt: '2024-11-05T18:25:52.995Z',
      updatedAt: '2024-11-06T08:35:53.394Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'tosoh-sysmex-integration-at-its-best-uk',
      name: 'Tosoh + Sysmex - Integration At Its Best (UK)',
      displayIndex: 46,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'Tosoh + Sysmex<br>Integration At Its Best (UK)',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '182409205889',
      createdAt: '2024-11-05T18:34:13.553Z',
      updatedAt: '2024-11-05T18:47:24.174Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'a-greener-nhs-flyer-uk',
      name: 'A Greener NHS flyer (UK)',
      displayIndex: 47,
      values: {
        title: 'A Greener NHS (UK)',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '182405117084',
      createdAt: '2024-11-05T18:40:41.494Z',
      updatedAt: '2024-11-05T18:47:35.956Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'tosoh-service-support-flyer_2024-uk',
      name: 'Tosoh Service & Support flyer_2024 (UK)',
      displayIndex: 48,
      values: {
        title: 'Tosoh Service & Support (UK)',
        document_type: {
          id: '6',
          name: 'Flyer',
          label: 'Flyer',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 2,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '185405900097',
      createdAt: '2025-01-27T10:49:50.947Z',
      updatedAt: '2025-06-03T13:16:31.850Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723-gr01-compact-with-big-impact',
      name: 'HLC-723® GR01 - Compact with Big Impact',
      displayIndex: 49,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'HLC-723® GR01 - Compact with Big Impact',
        document_type: {
          id: '5',
          name: 'Brochure',
          label: 'Brochure',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '190072756758',
      createdAt: '2025-05-13T10:04:14.661Z',
      updatedAt: '2025-06-16T15:54:01.500Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: 'hlc-723-gr01-compact-with-big-impact-spec-sheet',
      name: 'HLC-723® GR01 - Compact with Big Impact - Spec Sheet',
      displayIndex: 50,
      values: {
        product_type: {
          id: '1',
          name: 'A1c',
          label: 'A1c',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 0,
        },
        title: 'HLC-723® GR01 - Compact with Big Impact - Spec Sheet',
        document_type: {
          id: '4',
          name: 'Spec sheet',
          label: 'Spec sheet',
          type: 'option',
          createdAt: null,
          createdByUserId: 0,
          updatedAt: null,
          updatedByUserId: 0,
          order: 1,
        },
      },
      childTableId: '0',
      isSoftEditable: false,
    },
    {
      id: '190259645260',
      createdAt: '2025-05-17T08:34:04.487Z',
      updatedAt: '2025-05-17T08:34:04.487Z',
      publishedAt: '2025-06-19T13:33:57.995Z',
      path: null,
      name: null,
      displayIndex: 51,
      values: {},
      childTableId: '0',
      isSoftEditable: false,
    },
  ],
  type: 'STREAMING',
};

window.Tosoh.KioskDocumentsContent = {
  breadcrumbs: [
    {
      title: 'Home',
      url: {
        content_id: null,
        href: '/home',
        href_with_scheme: '/home',
        type: 'EXTERNAL',
      },
    },
    {
      title: 'Documents',
      url: {
        content_id: null,
        href: '/Documents',
        href_with_scheme: '/Documents',
        type: 'EXTERNAL',
      },
    },
  ],
  description:
    'Browse technical manuals, user guides, and official documentation to support your Tosoh products and services.',
  email_form: {
    follow_up_type_simple: null,
    form_id: null,
    form_type: null,
    gotowebinar_webinar_key: null,
    message: 'Thanks for submitting the form.',
    redirect_id: null,
    redirect_url: null,
    response_type: 'inline',
    webinar_id: null,
    webinar_source: null,
  },
  gated_form: {
    follow_up_type_simple: null,
    form_id: null,
    form_type: null,
    gotowebinar_webinar_key: null,
    message: 'Thanks for submitting the form.',
    redirect_id: null,
    redirect_url: null,
    response_type: 'inline',
    webinar_id: null,
    webinar_source: null,
  },
  gated_form_email: {
    follow_up_type_simple: null,
    form_id: null,
    form_type: null,
    gotowebinar_webinar_key: null,
    message: 'Thanks for submitting the form.',
    redirect_id: null,
    redirect_url: null,
    response_type: 'inline',
    webinar_id: null,
    webinar_source: null,
  },
  internal_version: false,
  search: {
    hubdb_column_id: 'title',
    title: 'Search',
  },
  title: 'Tosoh Kiosk Documents',
  topic_filters: {
    filters: [
      {
        filter_label: 'Document Type',
        hubdb_column_id: 'document_type',
        max: 0,
        min: 0,
        tolerance: 1,
        type: 'checkbox',
      },
      {
        filter_label: 'Product Type',
        hubdb_column_id: 'product_type',
        max: 0,
        min: 0,
        tolerance: 1,
        type: 'checkbox',
      },
    ],
    hubdb_table_id: 99968194,
  },
  type: 'module',
};
