import type { HubSpotMenu } from '../../../types/hubspot';
// import '../../../types/global';

const mockHeader = {
  mainNavigationMenu: {
    activeBranch: false,
    activeNode: false,
    blogNode: false,
    categoryId: null,
    children: [
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: 1,
        children: [],
        contentGroupId: null,
        contentType: 'site_page',
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Home',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 2,
        pageId: 170032951168,
        pageTitle: 'Sito Tosoh Emoglobine - home',
        parentGuid: null,
        slug: '',
        state: 'PUBLISHED_OR_SCHEDULED',
        subcategory: 'site_page',
        topLevelAncestorGuid: null,
        url: 'https://www.tosoh-diagnostics.it',
        urlParamStr: '',
        urlWithoutAnchor: 'https://www.tosoh-diagnostics.it',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: true,
        categoryId: 3,
        children: [],
        contentGroupId: 170127202144,
        contentType: 'blog',
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'News ed Eventi',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 1,
        pageId: null,
        pageTitle: 'Emoglobine news',
        parentGuid: null,
        slug: 'emoglobine-news',
        state: 'PUBLISHED',
        subcategory: null,
        topLevelAncestorGuid: null,
        url: 'https://www.tosoh-diagnostics.it/emoglobine-news',
        urlParamStr: '',
        urlWithoutAnchor: 'https://www.tosoh-diagnostics.it/emoglobine-news',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: 1,
        children: [],
        contentGroupId: null,
        contentType: 'site_page',
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Haemoglobin Academy',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 2,
        pageId: 171026340273,
        pageTitle: 'Sito Tosoh Emoglobine - academy',
        parentGuid: null,
        slug: 'academy',
        state: 'PUBLISHED_OR_SCHEDULED',
        subcategory: 'site_page',
        topLevelAncestorGuid: null,
        url: 'https://www.tosoh-diagnostics.it/academy',
        urlParamStr: '',
        urlWithoutAnchor: 'https://www.tosoh-diagnostics.it/academy',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: 1,
        children: [],
        contentGroupId: null,
        contentType: 'site_page',
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Contatti',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 2,
        pageId: 170144849694,
        pageTitle: 'Sito Tosoh Emoglobine - contact',
        parentGuid: null,
        slug: 'it/contact',
        state: 'PUBLISHED_OR_SCHEDULED',
        subcategory: 'site_page',
        topLevelAncestorGuid: null,
        url: 'https://www.tosoh-diagnostics.it/it/contact',
        urlParamStr: '',
        urlWithoutAnchor: 'https://www.tosoh-diagnostics.it/it/contact',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: 1,
        children: [],
        contentGroupId: null,
        contentType: 'site_page',
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: '<button>Servizi</button>',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 2,
        pageId: 171033984261,
        pageTitle: 'Sito Tosoh Emoglobine - access',
        parentGuid: null,
        slug: 'accesso',
        state: 'PUBLISHED_OR_SCHEDULED',
        subcategory: 'site_page',
        topLevelAncestorGuid: null,
        url: 'https://www.tosoh-diagnostics.it/accesso',
        urlParamStr: '',
        urlWithoutAnchor: 'https://www.tosoh-diagnostics.it/accesso',
      },
    ],
    contentGroupId: null,
    contentType: null,
    errorMessage: null,
    guid: null,
    isDeleted: false,
    isNonLinkingNode: false,
    isPublished: true,
    label: null,
    level: 0,
    linkTarget: null,
    live: true,
    nodeType: 3,
    pageId: null,
    pageTitle: null,
    parentGuid: null,
    slug: null,
    state: null,
    subcategory: null,
    topLevelAncestorGuid: null,
    url: null,
    urlParamStr: '',
    urlWithoutAnchor: 'null',
  },
} as {
  mainNavigationMenu: HubSpotMenu;
};

window.Tosoh = window.Tosoh || {};
window.Tosoh.Header = mockHeader;

export default mockHeader;
