const mockMenu = {
  activeBranch: false,
  activeNode: false,
  blogNode: false,
  categoryId: null,
  children: [
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [
                    {
                      activeBranch: false,
                      activeNode: false,
                      blogNode: true,
                      categoryId: 3,
                      children: [],
                      contentGroupId: 92043358884,
                      contentType: "blog",
                      errorMessage: null,
                      guid: null,
                      isDeleted: false,
                      isNonLinkingNode: false,
                      isPublished: true,
                      label: "Child Alpha",
                      level: 5,
                      linkTarget: null,
                      live: true,
                      nodeType: 1,
                      pageId: null,
                      pageTitle: "General Blog",
                      parentGuid: null,
                      slug: "blog",
                      state: "PUBLISHED",
                      subcategory: null,
                      topLevelAncestorGuid: null,
                      url: "http://22628452.hs-sites.com/blog-alpha",
                      urlParamStr: "",
                      urlWithoutAnchor: "http://22628452.hs-sites.com/blog-alpha",
                    },
                    {
                      activeBranch: false,
                      activeNode: false,
                      blogNode: true,
                      categoryId: 3,
                      children: [],
                      contentGroupId: 92043358884,
                      contentType: "blog",
                      errorMessage: null,
                      guid: null,
                      isDeleted: false,
                      isNonLinkingNode: false,
                      isPublished: true,
                      label: "Child Beta",
                      level: 5,
                      linkTarget: null,
                      live: true,
                      nodeType: 1,
                      pageId: null,
                      pageTitle: "General Blog",
                      parentGuid: null,
                      slug: "blog",
                      state: "PUBLISHED",
                      subcategory: null,
                      topLevelAncestorGuid: null,
                      url: "http://22628452.hs-sites.com/blog-alpha",
                      urlParamStr: "",
                      urlWithoutAnchor: "http://22628452.hs-sites.com/blog-alpha",
                    },
                  ],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Blog Submenu Alpha",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog-alpha",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog-alpha",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Our Services",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/services",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/services",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Consulting Submenu One",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/consulting-one",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/consulting-one",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Consulting Submenu Two",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/consulting-two",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/consulting-two",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Consulting Submenu Three",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/consulting-three",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/consulting-three",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Consulting Submenu Four",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/consulting-four",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/consulting-four",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Consulting",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/consulting",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/consulting",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Resources",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/resources",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/resources",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Contact Us",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/contact",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/contact",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/main-menu",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/main-menu",
        },

      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Products & Services",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Alpha",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-alpha",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-alpha",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Beta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-beta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-beta",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Gamma",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-gamma",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-gamma",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link - Longer",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/main-menu-longer",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/main-menu-longer",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Alpha",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-alpha",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-alpha",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Beta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-beta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-beta",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Gamma",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-gamma",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-gamma",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Menu Small",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/menu-small-2",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/menu-small-2",
        },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Areas of Expertise",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Delta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-delta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-delta",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Epsilon",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-epsilon",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-epsilon",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Longer Submenu Zeta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/longer-zeta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/longer-zeta",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link - Longer",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/main-menu-longer-2",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/main-menu-longer-2",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Delta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-delta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-delta",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Epsilon",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-epsilon",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-epsilon",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Short Submenu Zeta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/short-zeta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/short-zeta",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Menu Small",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/menu-small-3",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/menu-small-3",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Deepest Submenu Unique",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/deepest-submenu",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/deepest-submenu",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Deepest Menu",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/deepest-menu",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/deepest-menu",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Deepest Menu Beta",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/deepest-menu-beta",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/deepest-menu-beta",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/main-menu-4",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/main-menu-4",
        },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "About",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: true,
      categoryId: 3,
      children: [],
      contentGroupId: 92043358884,
      contentType: "blog",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Articles",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "General Blog",
      parentGuid: null,
      slug: "blog",
      state: "PUBLISHED",
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "http://22628452.hs-sites.com/patient-advocacy",
      urlParamStr: "",
      urlWithoutAnchor: "http://22628452.hs-sites.com/patient-advocacy",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: true,
      categoryId: 3,
      children: [],
      contentGroupId: 92043358884,
      contentType: "blog",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Careers",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "General Blog",
      parentGuid: null,
      slug: "blog",
      state: "PUBLISHED",
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "http://22628452.hs-sites.com/investors",
      urlParamStr: "",
      urlWithoutAnchor: "http://22628452.hs-sites.com/investors",
    },
  ],
  contentGroupId: null,
  contentType: null,
  errorMessage: null,
  guid: null,
  isDeleted: false,
  isNonLinkingNode: false,
  isPublished: true,
  label: null,
  level: 0,
  linkTarget: null,
  live: true,
  nodeType: 3,
  pageId: null,
  pageTitle: null,
  parentGuid: null,
  slug: null,
  state: null,
  subcategory: null,
  topLevelAncestorGuid: null,
  url: null,
  urlParamStr: "",
  urlWithoutAnchor: "null",
};

window.Tosoh = {
  mainNavigationMenu: mockMenu,
  mainNavigationCTAs: [
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'circle',
      menuIndex: 0,
      submenuIndex: null,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'pill',
      bgColor: 'lime',
      menuIndex: 0,
      submenuIndex: null,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'circle',
      bgColor: 'lime',
      menuIndex: 0,
      submenuIndex: 0,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'circle',
      menuIndex: 0,
      submenuIndex: 2,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'circle',
      bgColor: 'lime',
      menuIndex: 0,
      submenuIndex: 2,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      bgColor: 'lime',
      menuIndex: 1,
      submenuIndex: null,
    },
    {
      title: "Lorem Ipsum",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      link: "https://www.hubspot.com",
      linkLabel: "Learn More",
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'pill',
      bgColor: 'petrol',
      menuIndex: 1,
      submenuIndex: null,
    },
    {
      image: {
        src: "https://22628452.fs1.hubspotusercontent-na1.net/hubfs/22628452/inovation-center.jpg",
      },
      imageVariant: 'circle',
      bgColor: 'lime',
      menuIndex: 2,
      submenuIndex: null,
    },
  ],
  ...window.Tosoh,
}
