import type { HubSpotMenu } from '../../../types/hubspot';
// import '../../../types/global';

const mockHeader = {
  mainNavigationMenu: {
    activeBranch: false,
    activeNode: false,
    blogNode: false,
    categoryId: null,
    children: [
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [
                  {
                    activeBranch: false,
                    activeNode: false,
                    blogNode: false,
                    categoryId: null,
                    children: [
                      {
                        activeBranch: false,
                        activeNode: false,
                        blogNode: false,
                        categoryId: null,
                        children: [],
                        contentGroupId: null,
                        contentType: null,
                        errorMessage: null,
                        guid: null,
                        isDeleted: false,
                        isNonLinkingNode: false,
                        isPublished: true,
                        label: '5th',
                        level: 5,
                        linkTarget: null,
                        live: true,
                        nodeType: 3,
                        pageId: null,
                        pageTitle: null,
                        parentGuid: null,
                        slug: null,
                        state: null,
                        subcategory: null,
                        topLevelAncestorGuid: null,
                        url: '',
                        urlParamStr: '',
                        urlWithoutAnchor: '',
                      },
                    ],
                    contentGroupId: null,
                    contentType: null,
                    errorMessage: null,
                    guid: null,
                    isDeleted: false,
                    isNonLinkingNode: false,
                    isPublished: true,
                    label: '4th',
                    level: 4,
                    linkTarget: null,
                    live: true,
                    nodeType: 3,
                    pageId: null,
                    pageTitle: null,
                    parentGuid: null,
                    slug: null,
                    state: null,
                    subcategory: null,
                    topLevelAncestorGuid: null,
                    url: '',
                    urlParamStr: '',
                    urlWithoutAnchor: '',
                  },
                ],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: '3rd',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Thermo dynamics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Robotics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Optics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: '2nd',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: '1st',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Services',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Partnerships',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Agencies',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Life Sciences ',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '/',
        urlParamStr: '',
        urlWithoutAnchor: '/',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Resources',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '/',
        urlParamStr: '',
        urlWithoutAnchor: '/',
      },
    ],
    contentGroupId: null,
    contentType: null,
    errorMessage: null,
    guid: null,
    isDeleted: false,
    isNonLinkingNode: false,
    isPublished: true,
    label: null,
    level: 0,
    linkTarget: null,
    live: true,
    nodeType: 3,
    pageId: null,
    pageTitle: null,
    parentGuid: null,
    slug: null,
    state: null,
    subcategory: null,
    topLevelAncestorGuid: null,
    url: null,
    urlParamStr: '',
    urlWithoutAnchor: 'null',
  },
  auxiliaryMenu: {
    activeBranch: false,
    activeNode: false,
    blogNode: false,
    categoryId: null,
    children: [
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,

        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [
                  {
                    activeBranch: false,
                    activeNode: false,
                    blogNode: false,
                    categoryId: null,
                    children: [
                      {
                        activeBranch: false,
                        activeNode: false,
                        blogNode: false,
                        categoryId: null,
                        children: [],
                        contentGroupId: null,
                        contentType: null,
                        errorMessage: null,
                        guid: null,
                        isDeleted: false,
                        isNonLinkingNode: false,
                        isPublished: true,
                        label: '5th',
                        level: 5,
                        linkTarget: null,
                        live: true,
                        nodeType: 3,
                        pageId: null,
                        pageTitle: null,
                        parentGuid: null,
                        slug: null,
                        state: null,
                        subcategory: null,
                        topLevelAncestorGuid: null,
                        url: '',
                        urlParamStr: '',
                        urlWithoutAnchor: '',
                      },
                    ],
                    contentGroupId: null,
                    contentType: null,
                    errorMessage: null,
                    guid: null,
                    isDeleted: false,
                    isNonLinkingNode: false,
                    isPublished: true,
                    label: '4th',
                    level: 4,
                    linkTarget: null,
                    live: true,
                    nodeType: 3,
                    pageId: null,
                    pageTitle: null,
                    parentGuid: null,
                    slug: null,
                    state: null,
                    subcategory: null,
                    topLevelAncestorGuid: null,
                    url: '',
                    urlParamStr: '',
                    urlWithoutAnchor: '',
                  },
                ],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: '3rd',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,

                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Thermo dynamics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Robotics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Optics',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: '2nd',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: '1st',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '/',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Services',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Partnerships',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
      {
        activeBranch: false,
        activeNode: false,
        blogNode: false,
        categoryId: null,
        children: [
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
          {
            activeBranch: false,
            activeNode: false,
            blogNode: false,
            categoryId: null,
            children: [
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Navtext',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
              {
                activeBranch: false,
                activeNode: false,
                blogNode: false,
                categoryId: null,
                children: [],
                contentGroupId: null,
                contentType: null,
                errorMessage: null,
                guid: null,
                isDeleted: false,
                isNonLinkingNode: false,
                isPublished: true,
                label: 'Sub Naviation Text',
                level: 3,
                linkTarget: null,
                live: true,
                nodeType: 3,
                pageId: null,
                pageTitle: null,
                parentGuid: null,
                slug: null,
                state: null,
                subcategory: null,
                topLevelAncestorGuid: null,
                url: '',
                urlParamStr: '',
                urlWithoutAnchor: '',
              },
            ],
            contentGroupId: null,
            contentType: null,
            errorMessage: null,
            guid: null,
            isDeleted: false,
            isNonLinkingNode: false,
            isPublished: true,
            label: 'Digital Strategy',
            level: 2,
            linkTarget: null,
            live: true,
            nodeType: 3,
            pageId: null,
            pageTitle: null,
            parentGuid: null,
            slug: null,
            state: null,
            subcategory: null,
            topLevelAncestorGuid: null,
            url: '',
            urlParamStr: '',
            urlWithoutAnchor: '',
          },
        ],
        contentGroupId: null,
        contentType: null,
        errorMessage: null,
        guid: null,
        isDeleted: false,
        isNonLinkingNode: false,
        isPublished: true,
        label: 'Agencies',
        level: 1,
        linkTarget: null,
        live: true,
        nodeType: 3,
        pageId: null,
        pageTitle: null,
        parentGuid: null,
        slug: null,
        state: null,
        subcategory: null,
        topLevelAncestorGuid: null,
        url: '',
        urlParamStr: '',
        urlWithoutAnchor: '',
      },
    ],
    contentGroupId: null,
    contentType: null,
    errorMessage: null,
    guid: null,
    isDeleted: false,
    isNonLinkingNode: false,
    isPublished: true,
    label: null,
    level: 0,
    linkTarget: null,
    live: true,
    nodeType: 3,
    pageId: null,
    pageTitle: null,
    parentGuid: null,
    slug: null,
    state: null,
    subcategory: null,
    topLevelAncestorGuid: null,
    url: null,
    urlParamStr: '',
    urlWithoutAnchor: 'null',
  },
} as {
  mainNavigationMenu: HubSpotMenu;
  auxiliaryMenu: HubSpotMenu;
};

window.Tosoh = window.Tosoh || {};
window.Tosoh.Header = mockHeader;

export default mockHeader;
