import type { CCTComparisons } from '../../../types/hubdb';
import { IS_MOCK } from '../../utils/constants';

if (IS_MOCK) {
  window.Tosoh.CCT = {
    allInstruments: {
      limit: 1000,
      message: null,
      objects: [
        {
          access_level: {
            createdAt: 1758531503517,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'HPLC',
            labelTranslations: {},
            name: 'hplc',
            order: 0,
            type: 'option',
            updatedAt: 1758531503517,
            updatedByUserId: 69586742,
          },
          active: 1,
          clinician_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          company: {
            createdAt: 1758173117003,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Tosoh',
            labelTranslations: {},
            name: 'Tosoh',
            order: 0,
            type: 'option',
            updatedAt: 1758173117003,
            updatedByUserId: 69586742,
          },
          country_of_origin: {
            createdAt: 1758173117003,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'US',
            labelTranslations: {},
            name: 'US',
            order: 0,
            type: 'option',
            updatedAt: 1758173117003,
            updatedByUserId: 69586742,
          },
          hs_child_table_id: 0,
          hs_created_at: 1758173184147,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277162252520,
          hs_initial_published_at: 1758173355724,
          hs_is_edited: false,
          hs_published_at: 1758565622479,
          hs_updated_at: 1758531541521,
          hs_updated_by_user_id: 69586742,
          lab_man_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          lab_staff_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          procurement_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          product_line: {
            createdAt: 1758182405338,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Big Immuno Assay',
            labelTranslations: {},
            name: 'big_immuno_assay',
            order: 0,
            type: 'option',
            updatedAt: 1758182405338,
            updatedByUserId: 69586742,
          },
          product_name: 'G11',
        },
        {
          active: 1,
          clinician_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          company: {
            createdAt: 1758173318671,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Siemens',
            labelTranslations: {},
            name: 'SIEMENS',
            order: 1,
            type: 'option',
            updatedAt: 1758173318671,
            updatedByUserId: 69586742,
          },
          country_of_origin: {
            createdAt: 1758173334837,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Germany',
            labelTranslations: {},
            name: 'Germany',
            order: 1,
            type: 'option',
            updatedAt: 1758173334837,
            updatedByUserId: 69586742,
          },
          hs_child_table_id: 0,
          hs_created_at: 1758173288841,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277209724134,
          hs_initial_published_at: 1758173355724,
          hs_is_edited: false,
          hs_published_at: 1758565622479,
          hs_updated_at: 1758565329553,
          hs_updated_by_user_id: 69586742,
          lab_man_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          lab_staff_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          procurement_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          product_name: 'D 100',
          sufficient_data_status: {
            createdAt: 1758565285511,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Sufficient Data',
            labelTranslations: {},
            name: 'sufficient_data',
            order: 0,
            type: 'option',
            updatedAt: 1758565466979,
            updatedByUserId: 69586742,
          },
        },
        {
          access_level: {
            createdAt: 1758531503517,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'CL',
            labelTranslations: {},
            name: 'cl',
            order: 1,
            type: 'option',
            updatedAt: 1758531503517,
            updatedByUserId: 69586742,
          },
          active: 1,
          clinician_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          company: {
            createdAt: 1758173117003,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Tosoh',
            labelTranslations: {},
            name: 'Tosoh',
            order: 0,
            type: 'option',
            updatedAt: 1758173117003,
            updatedByUserId: 69586742,
          },
          country_of_origin: {
            createdAt: 1758173117003,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'US',
            labelTranslations: {},
            name: 'US',
            order: 0,
            type: 'option',
            updatedAt: 1758173117003,
            updatedByUserId: 69586742,
          },
          hs_child_table_id: 0,
          hs_created_at: 1758189296819,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277296949474,
          hs_initial_published_at: 1758189299092,
          hs_is_edited: false,
          hs_published_at: 1758565622479,
          hs_updated_at: 1758531544125,
          hs_updated_by_user_id: 69586742,
          lab_man_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          lab_staff_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          procurement_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          product_line: {
            createdAt: 1758182405338,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'HPLC',
            labelTranslations: {},
            name: 'hplc',
            order: 1,
            type: 'option',
            updatedAt: 1758182405338,
            updatedByUserId: 69586742,
          },
          product_name: 'G12',
        },
        {
          active: 1,
          clinician_benefits:
            '<div data-test-id="rich-text-cell-text">\n<p>I am siemens</p>\n</div>\n<div>&nbsp;</div>',
          company: {
            createdAt: 1758173318671,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Siemens',
            labelTranslations: {},
            name: 'SIEMENS',
            order: 1,
            type: 'option',
            updatedAt: 1758173318671,
            updatedByUserId: 69586742,
          },
          country_of_origin: {
            createdAt: 1758173334837,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Germany',
            labelTranslations: {},
            name: 'Germany',
            order: 1,
            type: 'option',
            updatedAt: 1758173334837,
            updatedByUserId: 69586742,
          },
          hs_child_table_id: 0,
          hs_created_at: 1758285164753,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277744467150,
          hs_initial_published_at: 1758285191030,
          hs_is_edited: false,
          hs_published_at: 1758565622479,
          hs_updated_at: 1758565333407,
          hs_updated_by_user_id: 69586742,
          lab_man_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          lab_staff_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          procurement_benefits: 'I am siemens',
          product_name: 'D 120',
          sufficient_data_status: {
            createdAt: 1758565285511,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Sufficient Data',
            labelTranslations: {},
            name: 'sufficient_data',
            order: 0,
            type: 'option',
            updatedAt: 1758565466979,
            updatedByUserId: 69586742,
          },
        },
        {
          active: 1,
          clinician_benefits:
            '<div data-test-id="rich-text-cell-text">\n<p>I am siemens</p>\n</div>\n<div>&nbsp;</div>',
          company: {
            createdAt: 1758173318671,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Siemens',
            labelTranslations: {},
            name: 'SIEMENS',
            order: 1,
            type: 'option',
            updatedAt: 1758173318671,
            updatedByUserId: 69586742,
          },
          country_of_origin: {
            createdAt: 1758173334837,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Germany',
            labelTranslations: {},
            name: 'Germany',
            order: 1,
            type: 'option',
            updatedAt: 1758173334837,
            updatedByUserId: 69586742,
          },
          hs_child_table_id: 0,
          hs_created_at: 1758285625124,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277760135404,
          hs_initial_published_at: 1758285633315,
          hs_is_edited: false,
          hs_published_at: 1758565622479,
          hs_updated_at: 1758565471073,
          hs_updated_by_user_id: 69586742,
          lab_man_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          lab_staff_benefits:
            '<span>To keep his different stakeholders (Clinicians, Laboratory employees and Procurement Manager) satisfied with the laboratory production and running costs.<br>To work with reliable and robust instruments that make the daily life of the laboratory staff smooth and easy.<br>To provide accurate and fast results for the Clinicians allowing them to take care of the patients efficiently.<br>To pass accreditation and EQA schemes.</span>',
          procurement_benefits: 'I am siemens',
          product_name: 'D500',
          sufficient_data_status: {
            createdAt: 1758565466979,
            createdByUserId: 69586742,
            id: 3,
            isHubspotDefined: false,
            label: 'Non Sufficient Data',
            labelTranslations: {},
            name: 'non_sufficient_data',
            order: 1,
            type: 'option',
            updatedAt: 1758565466979,
            updatedByUserId: 69586742,
          },
        },
      ],
      offset: 0,
      total: 5,
      totalCount: 5,
    },
    activeCompetitorInstruments: [],
    allProductLines: [
      {
        createdAt: 1758182405338,
        createdByUserId: 69586742,
        id: 1,
        isHubspotDefined: false,
        label: 'Big Immuno Assay',
        labelTranslations: {},
        name: 'big_immuno_assay',
        order: 0,
        type: 'option',
        updatedAt: 1758182405338,
        updatedByUserId: 69586742,
      },
      {
        createdAt: 1758182405338,
        createdByUserId: 69586742,
        id: 2,
        isHubspotDefined: false,
        label: 'HPLC',
        labelTranslations: {},
        name: 'hplc',
        order: 1,
        type: 'option',
        updatedAt: 1758182405338,
        updatedByUserId: 69586742,
      },
    ],
    instrumentsBasedOnProductLine: ['G11', 'G12'],
  };

  window.Tosoh.CCTDetails = {
    comparisonRows: {
      limit: 1000,
      message: null,
      objects: [
        {
          category: {
            createdAt: 1758173786505,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Basic Specification',
            labelTranslations: {},
            name: 'basic_specification',
            order: 0,
            type: 'option',
            updatedAt: 1758173786505,
            updatedByUserId: 69586742,
          },
          clinician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          competitor_instrument_name: [
            {
              id: 277209724134,
              isPublished: true,
              name: 'D 100',
              type: 'foreignid',
            },
          ],
          hs_child_table_id: 0,
          hs_created_at: 1758173392823,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277162252521,
          hs_initial_published_at: 1758173859775,
          hs_is_edited: false,
          hs_path: '',
          hs_published_at: 1758218124334,
          hs_updated_at: 1758180823977,
          hs_updated_by_user_id: 69586742,
          lab_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          lab_technician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          procurement_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          status: {
            createdAt: 1758173537198,
            createdByUserId: 69586742,
            id: 1,
            isHubspotDefined: false,
            label: 'Advantage',
            labelTranslations: {},
            name: 'Advantage',
            order: 0,
            type: 'option',
            updatedAt: 1758173537198,
            updatedByUserId: 69586742,
          },
          tosoh_instrument_name: [
            {
              id: 277162252520,
              isPublished: true,
              name: 'G11',
              type: 'foreignid',
            },
          ],
        },
        {
          category: {
            createdAt: 1758173786505,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Application Range',
            labelTranslations: {},
            name: 'application_range',
            order: 1,
            type: 'option',
            updatedAt: 1758173786505,
            updatedByUserId: 69586742,
          },
          clinician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          competitor_instrument_name: [
            {
              id: 277209724134,
              isPublished: true,
              name: 'D 100',
              type: 'foreignid',
            },
          ],
          hs_child_table_id: 0,
          hs_created_at: 1758173839899,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277162263780,
          hs_initial_published_at: 1758173859775,
          hs_is_edited: false,
          hs_path: '',
          hs_published_at: 1758218124334,
          hs_updated_at: 1758174849907,
          hs_updated_by_user_id: 69586742,
          lab_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          lab_technician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          procurement_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          status: {
            createdAt: 1758173537198,
            createdByUserId: 69586742,
            id: 2,
            isHubspotDefined: false,
            label: 'Neutral',
            labelTranslations: {},
            name: 'Neutral',
            order: 1,
            type: 'option',
            updatedAt: 1758173537198,
            updatedByUserId: 69586742,
          },
          tosoh_instrument_name: [
            {
              id: 277162252520,
              isPublished: true,
              name: 'G11',
              type: 'foreignid',
            },
          ],
        },
        {
          category: {
            createdAt: 1758173786505,
            createdByUserId: 69586742,
            id: 3,
            isHubspotDefined: false,
            label: 'Measurement Modes',
            labelTranslations: {},
            name: 'measurement_modes',
            order: 2,
            type: 'option',
            updatedAt: 1758173786505,
            updatedByUserId: 69586742,
          },
          clinician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          competitor_instrument_name: [
            {
              id: 277209724134,
              isPublished: true,
              name: 'D 100',
              type: 'foreignid',
            },
          ],
          hs_child_table_id: 0,
          hs_created_at: 1758173851592,
          hs_created_by_user_id: 69586742,
          hs_deleted_at: 0,
          hs_id: 277162263781,
          hs_initial_published_at: 1758173859775,
          hs_is_edited: false,
          hs_published_at: 1758218124334,
          hs_updated_at: 1758173857755,
          hs_updated_by_user_id: 69586742,
          lab_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          lab_technician:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          procurement_manager:
            '<span>Time and cost-efficient use of<br>instrument; low applications can<br>be run on the same instrument</span>',
          status: {
            createdAt: 1758173537198,
            createdByUserId: 69586742,
            id: 3,
            isHubspotDefined: false,
            label: 'Disadvantage',
            labelTranslations: {},
            name: 'Disadvantage',
            order: 2,
            type: 'option',
            updatedAt: 1758173537198,
            updatedByUserId: 69586742,
          },
          tosoh_instrument_name: [
            {
              id: 277162252520,
              isPublished: true,
              name: 'G11',
              type: 'foreignid',
            },
          ],
        },
      ],
      offset: 0,
      total: 3,
      totalCount: 3,
    } as CCTComparisons,
  };
}
