export const mockResponse = {
  total: 35,
  results: [
    {
      id: '272648207560',
      createdAt: '2025-09-05T07:35:11.658Z',
      updatedAt: '2025-09-05T07:35:11.658Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Dr. med. Claudia Frömmel',
        presenter_1_name: 'Dr. med. Matthias Weber',
        presenter_1_location: 'Facharzt für Laboratoriumsmedizin, Bioscientia MVZ Labor Karlsruhe',
        presenter_2_image:
          'https://landing.tosoh-diagnostics.com/hubfs/claudia_frommel.jpg,120,169',
        presenter_1_title: 'Hämoglobinopathien – Grundlagen und Diagnostik',
        webinar_title: '2021-3 Webinar Reihe Hämoglobinopathien in Deutschland',
        priority: '3',
        webinar_subtext:
          '<p>Hämoglobinopathien – Grundlagen und Diagnostik</p>\n<p>Hämoglobinopathien – neue Entwicklung Neugeborenenscreening auf Sichelzellkrankheit in Deutschland 2021: Herausforderungen an die Diagnostik im Routinelabor</p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/weber.jpg',
          width: 120,
          height: 180,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Hämoglobinopathien – neue Entwicklung Neugeborenenscreening auf Sichelzellkrankheit in Deutschland 2021: Herausforderungen an die Diagnostik im Routinelabor',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207561',
      createdAt: '2025-09-05T07:35:11.659Z',
      updatedAt: '2025-09-05T07:35:11.659Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Priv.-Doz. Dr. med. Armin Soave<br>UKE, Hamburg',
        presenter_1_name: 'Prof. Dr. med Michael Zitzmann',
        presenter_1_location: 'Universitätsklinikum Münster',
        presenter_2_image:
          'https://landing.tosoh-diagnostics.com/hubfs/Urology/Armin%20Soave.jpeg,96,115',
        presenter_1_title: 'Sexualhormonbindendes Globulin – gibt es eine klinische Relevanz?',
        webinar_title: '2022-1 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '6',
        webinar_subtext:
          '<h3 style="text-align: left;"><span style="color: #000000;">Wichtige Biomarker in der Urologie</span></h3>\n<p><span>Zunächst wird der Parameter Sexualhormonbindendes Globulin im Kontext der klinischen Relevanz betrachtet</span><span>.&nbsp;</span><span>Die freien Androgene sind in der Beurteilung häufig von entscheidender Bedeutung, so dass hier das SHBG&nbsp;</span><span>als zweiter Parameter verwendet werden muss.&nbsp;</span><span>Das Prostataspezifische Antigen, seit Jahren ein Marker für die Früherkennung des Prostatakarzinoms,&nbsp;</span><span>soll hier noch einmal genauer beleuchtet werden.</span><span></span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Urology/M.zittmann.jpg',
          width: 96,
          height: 115,
          altText: '',
          type: 'image',
        },
        presenter_2_title: 'Der Stellenwert des PSA beim Prostatakarzinom',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207562',
      createdAt: '2025-09-05T07:35:11.660Z',
      updatedAt: '2025-09-05T07:35:11.660Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Prof. Dr. med. Dipl. Biol. Astrid Petersmann',
        presenter_1_name: 'Dr. med. Matthias Weber',
        presenter_1_location: 'Facharzt für Laboratoriumsmedizin, Bioscientia MVZ Labor Karlsruhe',
        presenter_2_image:
          'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/Petersmann.jpg,160,174',
        presenter_1_title: 'Einflüsse von Hämoglobinopathien auf die HbA1c-Bestimmung',
        webinar_title: '2021-1 Webinar Reihe Verschiedene Einflussgrößen auf die HbA1c-Messung',
        priority: '1',
        webinar_subtext:
          '<p>Einflüsse von Hämoglobinopathien auf die HbA1c-Bestimmung</p>\n<p>HbA1c: Müssen wir das Altern berücksichtigen?</p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/weber.jpg',
          width: 120,
          height: 180,
          altText: '',
          type: 'image',
        },
        presenter_2_title: 'HbA1c: Müssen wir das Altern berücksichtigen?',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207563',
      createdAt: '2025-09-05T07:35:11.661Z',
      updatedAt: '2025-09-05T07:35:11.661Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_1_name: 'Tanja Erden',
        presenter_1_title: 'Tosoh',
        webinar_title:
          '2021-2 Webinar Reihe HbA1c, Hämoglobinopathien und Chromatogramminterpretation',
        priority: '2',
        webinar_subtext:
          '<p><span>Im Webinar werden unter anderem die Einflüsse von Hämoglobinopathien auf die HbA1c-Messung gezeigt. Anschließend wird an vielen Beispiel-Chromatogrammen veranschaulicht, welche HbA1c-Werte valide sind oder wo eine Interferenz auftreten kann. Das Webinar unterstützt Sie bei der Entscheidung in der täglichen Routine.</span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/tanja.png',
          width: 194,
          height: 259,
          altText: '',
          type: 'image',
        },
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207564',
      createdAt: '2025-09-05T07:35:11.662Z',
      updatedAt: '2025-09-05T07:35:11.662Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Dr. med. Caroline Stobe',
        presenter_1_name: 'Prof. Dr. med. Dipl. Biol. Astrid Petersmann',
        presenter_1_location:
          'Universitätsinstitut für Klinische Chemie und Laboratoriumsmedizin Oldenburg',
        presenter_2_image: 'https://landing.tosoh-diagnostics.com/hubfs/Stobe.jpg,120,180',
        presenter_1_title: 'Medizinische Anforderungen an die Messqualität der HbA1c-Bestimmungen',
        webinar_title: '2021-4 Webinar Reihe HbA1c in der neuen RiliBÄK',
        priority: '4',
        webinar_subtext:
          '<p>Medizinische Anforderungen an die Messqualität der HbA1c-Bestimmungen</p>\n<p>Externe Qualitätskontrolle für HbA1c: Ringversuche und internationale Standardisierung</p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/Petersmann.jpg',
          width: 160,
          height: 174,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Externe Qualitätskontrolle für HbA1c: Ringversuche und internationale Standardisierung',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207565',
      createdAt: '2025-09-05T07:35:11.663Z',
      updatedAt: '2025-09-05T07:35:11.663Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Dr. med. Abass Eidizadeh, Dr. phil. nat. Bozena Czech-Zechmeister',
        presenter_1_name: 'Dr. med. Matthias Weber',
        presenter_1_location: 'Facharzt für Laboratoriumsmedizin, Bioscientia MVZ Labor Karlsruhe',
        presenter_2_image: 'https://landing.tosoh-diagnostics.com/hubfs/Eidizadeh1.jpg,120,180',
        presenter_1_title: ' Einflüsse von Hämoglobinopathien auf die HbA1c-Bestimmung',
        webinar_title: '2021-5 Webinar Reihe HbA1c-Messung: Achtung bei Hämoglobinopathien',
        priority: '5',
        webinar_subtext:
          '<p>Einflüsse von Hämoglobinopathien auf die HbA1c-Bestimmung</p>\n<p>Vergleich der Auswirkungen von Hämoglobinvarianten und hohen HbF-Werten auf die HbA1c-Messung in unterschiedlichen Methoden</p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/email/webinarseries2021/weber.jpg',
          width: 120,
          height: 180,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Vergleich der Auswirkungen von Hämoglobinvarianten und hohen HbF-Werten auf die HbA1c-Messung in unterschiedlichen Methoden',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207566',
      createdAt: '2025-09-05T07:35:11.664Z',
      updatedAt: '2025-09-05T07:35:11.664Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Uli Früh',
        presenter_1_name: 'Prof. Dr. Christian Doehn',
        presenter_1_location: 'Facharzt für Urologie, Urologikum Lübeck',
        presenter_2_image: 'https://landing.tosoh-diagnostics.com/hubfs/Uli%20Fruh.jpeg,189,245',
        presenter_1_title: 'Update: Markerdiagnostik beim Hodentumor',
        webinar_title: '2022-2 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '7',
        webinar_subtext:
          '<h3 style="text-align: left;"><span style="color: #000000;">Biomarker beim Hodentumor und Abrechnung von Laborleistungen</span></h3>\n<p><span></span><span>Biomarker sind in der Urologie ein wichtiger Bestandteil der Diagnostik. Es werden wichtige Marker, die bei der Diagnostik und Therapie des Hodentumors eine Rolle spielen, beschrieben. Ein Ausblick soll außerdem auf mögliche zukünftige Marker hinweisen.<br><br>Anschließend gehen wir auf unterschiedliche Fragestellungen zur Abrechnung von Laborleistungen im urologischen Labor ein. Was kann ich im EBM und in der GOÄ abrechnen? Was muss ich bei der KV-Abrechnung wissen und beachten? Wo sind im EBM Fallstricke? Was ist bezüglich der Laborvergütung bei der neuen GOÄ zu erwarten?</span><span></span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Christian%20Doehn.jpeg',
          width: 79,
          height: 94,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Abrechnung von Laborleistungen – was ich schon immer dazu wissen wollte',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207567',
      createdAt: '2025-09-05T07:35:11.665Z',
      updatedAt: '2025-09-05T07:35:11.665Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Uli Früh',
        presenter_1_name: 'Prof. Dr. Christian Doehn',
        presenter_1_location: 'Facharzt für Urologie, Urologikum Lübeck',
        presenter_2_image: 'https://landing.tosoh-diagnostics.com/hubfs/Uli%20Fruh.jpeg,189,245',
        presenter_1_title: 'Update: Markerdiagnostik beim Hodentumor',
        webinar_title: '2022-2 Webinare TOSOH DIAGNOSTIK FORUM',
        priority: '8',
        webinar_subtext:
          '<h3 style="text-align: left;"><span style="color: #000000;">Biomarker beim Hodentumor und Abrechnung von Laborleistungen</span></h3>\n<p><span></span><span>Biomarker sind in der Urologie ein wichtiger Bestandteil der Diagnostik. Es werden wichtige Marker, die bei der Diagnostik und Therapie des Hodentumors eine Rolle spielen, beschrieben. Ein Ausblick soll außerdem auf mögliche zukünftige Marker hinweisen.<br><br>Anschließend gehen wir auf unterschiedliche Fragestellungen zur Abrechnung von Laborleistungen im urologischen Labor ein. Was kann ich im EBM und in der GOÄ abrechnen? Was muss ich bei der KV-Abrechnung wissen und beachten? Wo sind im EBM Fallstricke? Was ist bezüglich der Laborvergütung bei der neuen GOÄ zu erwarten?</span><span></span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Christian%20Doehn.jpeg',
          width: 79,
          height: 94,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Abrechnung von Laborleistungen – was ich schon immer dazu wissen wollte',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207568',
      createdAt: '2025-09-05T07:35:11.666Z',
      updatedAt: '2025-09-05T07:35:11.666Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_1_name: 'Tanja Erden',
        presenter_1_location: 'Tosoh',
        presenter_1_title: 'HbA1c, Hämoglobinopathien und Chromatogramminterpretation G8 und G11',
        webinar_title: '2022-3 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '9',
        webinar_subtext:
          '<h3 style="text-align: left;"><span style="color: #000000;"><span>HbA1c, Hämoglobinopathien und Chromatogramminterpretation G8 und G11</span></span></h3>\n<p><span><br></span><span></span><span></span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/tanja%20erden.jpeg',
          width: 250,
          height: 245,
          altText: '',
          type: 'image',
        },
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207569',
      createdAt: '2025-09-05T07:35:11.667Z',
      updatedAt: '2025-09-05T07:35:11.667Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Prof. Dr. med. Guiseppe Lippi ',
        presenter_1_name: 'Linda Raupach',
        presenter_1_location: 'Biologin Zell- und Mikrobiologie, Universität Zürich ',
        presenter_2_image:
          'https://landing.tosoh-diagnostics.com/hubfs/Prof.%20Lippi%20High%20Resolution.jpg,741,877',
        presenter_1_title: 'Toxoplasmose in der Schwangerschaft ',
        webinar_title: '2022-4 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '10',
        webinar_subtext:
          '<p>Aktuelle Themen in der Infektiologie</p>\n<p><span data-contrast="auto">In diesem Webinar berichten wir über zwei Erkrankungen: Toxoplasmose und Covid-19.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>\n<p><span data-contrast="auto">Es werden Folgen einer Toxoplasmose-Erkrankung in der Schwangerschaft beschrieben.&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>\n<p><span data-contrast="auto">Bei der Covid-19 Diagnostik werden unterschiedliche Teste hinsichtlich ihrer Aussagekraft innerhalb bestimmter Stadien der Erkrankung dargestellt.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Laura-2.jpg',
          width: 130,
          height: 130,
          altText: '',
          type: 'image',
        },
        presenter_2_title: 'The different aspects of Covid-19 diagnostics ',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207571',
      createdAt: '2025-09-05T07:35:11.669Z',
      updatedAt: '2025-09-05T07:35:11.669Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Prof. Dr. med. Guiseppe Lippi ',
        presenter_1_name: 'Linda Raupach',
        presenter_1_location: 'Biologin Zell- und Mikrobiologie, Universität Zürich ',
        presenter_2_image:
          'https://landing.tosoh-diagnostics.com/hubfs/Prof.%20Lippi%20High%20Resolution.jpg,741,877',
        presenter_1_title: 'Toxoplasmose in der Schwangerschaft ',
        webinar_title: '2022-4 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '10',
        webinar_subtext:
          '<p>Aktuelle Themen in der Infektiologie</p>\n<p><span data-contrast="auto">In diesem Webinar berichten wir über zwei Erkrankungen: Toxoplasmose und Covid-19.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>\n<p><span data-contrast="auto">Es werden Folgen einer Toxoplasmose-Erkrankung in der Schwangerschaft beschrieben.&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>\n<p><span data-contrast="auto">Bei der Covid-19 Diagnostik werden unterschiedliche Teste hinsichtlich ihrer Aussagekraft innerhalb bestimmter Stadien der Erkrankung dargestellt.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Laura-2.jpg',
          width: 130,
          height: 130,
          altText: '',
          type: 'image',
        },
        presenter_2_title: 'The different aspects of Covid-19 diagnostics ',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
    {
      id: '272648207572',
      createdAt: '2025-09-05T07:35:11.670Z',
      updatedAt: '2025-09-05T07:35:11.670Z',
      publishedAt: '2025-09-05T08:47:28.825Z',
      path: null,
      name: null,
      values: {
        presenter_2_name: 'Rafael Cano-Garcia',
        presenter_1_name: 'Ivo Beyaert',
        presenter_1_location: 'DIAG WISS, Berlin',
        presenter_2_image: 'https://landing.tosoh-diagnostics.com/hubfs/rafael.jpeg,237,254',
        presenter_1_title:
          'Rili-BÄK im Urologischen Labor – interne und externe Qualitätssicherung ',
        webinar_title: '2022-5 Webinar TOSOH DIAGNOSTIK FORUM',
        priority: '11',
        webinar_subtext:
          '<p><strong><span data-contrast="auto">Rili-BÄK: Interne und externe Qualitätssicherung leicht gemacht</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>\n<p><span data-contrast="auto">Diese Webinar gibt einen Überblick über die Vorgaben der Rili-BÄK und soll niedergelassenen Urol</span><span data-contrast="auto">o</span><span data-contrast="auto">gen eine Hilfestellung bei der Umsetzung und Durchführung der Qualitätssicherung geben. Was ist Interne Qualitätssicherung und warum muss ich das machen? Was ist Externe Qualitätssicherung und wie oft und an welchen Ringversuchen muss ich teilnehmen?</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>',
        presenter_1_image: {
          url: 'https://landing.tosoh-diagnostics.com/hubfs/Ivo%20Beyaert.jpg',
          width: 242,
          height: 339,
          altText: '',
          type: 'image',
        },
        presenter_2_title:
          'Interne Qualitätskontrollen, QMMA und Qualitätssicherung leicht gemacht ',
      },
      isSoftEditable: false,
      childTableId: '0',
    },
  ],
  paging: {
    next: {
      offset: 12,
      link: 'https://api.hubapi.com/cms/v3/hubdb/tables/webinars/rows?deactivate__eq=false&offset=12&limit=12&properties=webinar_title%2Cpriority%2Cwebinar_subtext%2Cpresenter_1_image%2Cpresenter_1_name%2Cpresenter_1_title%2Cpresenter_1_location%2Cpresenter_2_image%2Cpresenter_2_name%2Cpresenter_2_title',
    },
  },
  type: 'RANDOM_ACCESS',
};
